#----- Tmux options
set -g default-terminal "tmux-256color"

# Set tmux copy mode to vi bindings - prefix-[
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer

# Turn mouse off 
set -g mouse off

# Keep tmux daemon running in the background
set -s exit-empty off

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Turn off automatic renaming
set-option -wg allow-rename "off"

# Put status bar at the top
set-option -g status-position top

# Increase history limit
set-option -g history-limit 5000

# Toggle between last window
bind Space last-window

# Switch between windows 
bind C-l next-window
bind C-h previous-window

set -g status-interval 2

# Catppuccin theme configuration
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "left"

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text " #W"

#----- Installed plugins
# install prefix+I, update prefix+U, remove prefix+m+u
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "catppuccin/tmux"
set -g @plugin "27medkamal/tmux-session-wizard"

#----- Plugin configuration

set -g status-left "#{E:@catppuccin_status_session} "
set -g status-right ""

# Session wizard - open with prefix+p
set -g @session-wizard "p" 

#----- Running TPM  
run "~/.config/tmux/plugins/tpm/tpm"

# Use - and _ for splitting windows
unbind "'"
unbind %
bind - split-window -h
bind _ split-window -v
